version: 2

models:
  - name: customers
    description: One record per customer
    columns:
      - name: customer_id
        description: Primary key
        tests:
          - unique
          - not_null
      - name: first_order_date
        description: NULL when a customer has not yet placed an order.

  - name: orders
    description: This model cleans up order data. Granularity is order.
    columns:
      - name: customer_id
        description: Customer id
        tests:
          - not_null
      - name: order_id
        description: Order id